version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=todolist
    depends_on:
      - db
    networks:
      - monitoring

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todolist
    ports:
      - "6033:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitoring

volumes:
  db_data:

networks:
  monitoring: