version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - monitoring

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "6033:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - monitoring

volumes:
  db_data:

networks:
  monitoring:
    driver: bridge
