services:
  app:
    image: lisandrovazquez/todo-list:1.0.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=todolist

    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todolist
    ports:
      - "6033:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: