apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: proyecto-final-cf
spec:
  replicas: 3  # Aumentado para alta disponibilidad
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: lisandrovazquez/proyecto-final-cf:latest
        envFrom:
        - secretRef:
            name: mysql-credentials  # Usando Secret para credenciales
        - configMapRef:
            name: app-config         # Usando ConfigMap para otras variables
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: proyecto-final-cf
spec:
  type: LoadBalancer  #LoadBalancer para asignar una IP pública
  ports:
  - port: 3000
    targetPort: 3000 
  selector:
    app: app
