name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  compress-and-store:
    name: Compress and Store k8s Artifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compress k8s folder
      run: tar -czf k8s.tar.gz -C ./k8s .

    - name: Upload k8s artifact
      uses: actions/upload-artifact@v3
      with:
        name: k8s-artifact
        path: k8s.tar.gz

  deploy:
    name: Deploy k8s Resources
    needs: compress-and-store
    runs-on: ubuntu-latest

    steps:
    - name: Download k8s artifact
      uses: actions/download-artifact@v3
      with:
        name: k8s-artifact
        path: .

    - name: Add SSH key (Production only)
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload k8s artifact to server
      run: scp -o StrictHostKeyChecking=no k8s.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:sistemas

    - name: Extract k8s on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        mkdir -p sistemas/k8s
        tar -xzf sistemas/k8s.tar.gz -C istemas/k8s
        rm sistemas/k8s.tar.gz
        EOF

    - name: Deploy to Kubernetes
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd sistemas/k8s
        kubectl apply -f .
        kubectl get all -n proyecto-final-cf
        EOF
