name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key (Production only)
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Verify k8s folder exists
      run: ls -l ./k8s

    - name: Upload compressed k8s folder
      run: scp -o StrictHostKeyChecking=no k8s.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/sistemas

    - name: Extract k8s folder on remote server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        mkdir -p /home/ubuntu/sistemas/k8s
        tar -xzf /home/ubuntu/sistemas/k8s.tar.gz -C /home/ubuntu/sistemas/k8s
        rm /home/ubuntu/sistemas/k8s.tar.gz
        EOF
    - name: Deploy to EC2 (Production only)
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /home/ubuntu/sistemas/k8s
        kubectl apply -f .
        kubectl get all -n proyecto-final-cf
        EOF
